# Generated by Django 6.0.6 on 2026-07-07 13:10

import cuentas.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', cuentas.models.UsuarioManager()),
            ],
        ),
    ]
