# Generated by Django 6.0.6 on 2026-07-07 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo_equipo', models.CharField(max_length=60)),
                ('falla_reportada', models.TextField()),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('tiene_garantia', models.BooleanField(default=False)),
                ('garantia_hasta', models.DateField(blank=True, null=True)),
                ('estado_fisico', models.TextField(help_text='Golpes, daño por agua, marcas visibles al ingresar')),
                ('accesorios', models.CharField(blank=True, max_length=255)),
                ('_password_cifrada', models.BinaryField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('MESA_TRABAJO', 'Mesa de trabajo'), ('REPARADO', 'Reparado'), ('ENTREGADO', 'Entregado')], default='INGRESADO', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_mesa_trabajo', models.DateTimeField(blank=True, null=True)),
                ('fecha_reparado', models.DateTimeField(blank=True, null=True)),
                ('fecha_entregado', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='clientes.cliente')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='equipos.equipo')),
                ('subida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='equipos.equipo')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
